name: cupertino_battery_indicator
description: A simple widget to display battery charge inspired by the Cupertino design.
version: 1.2.0

homepage: https://github.com/ricardoboss/cupertino_battery_indicator
repository: https://github.com/ricardoboss/cupertino_battery_indicator

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
