name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 5 1 * *'

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: flutter-actions/setup-flutter@v3

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.os }}-flutter

      - name: Install dependencies
        run: dart pub get --enforce-lockfile

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze --fatal-infos

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        channel: [stable, beta, dev]

    steps:
      - uses: actions/checkout@v4
      - uses: flutter-actions/setup-flutter@v3
        with:
          channel: ${{ matrix.channel }}

      - uses: actions/cache@v4
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.os }}-flutter-${{ matrix.channel }}
          restore-keys: |
            ${{ runner.OS }}-flutter

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test
